using System;
using System.Collections.Generic;
using System.Globalization;

namespace LocalizationLib
{
    /// <summary>
    /// Внешняя библиотека локализации. Предоставляет строки для русского и английского языков.
    /// </summary>
    public static class StringsProvider
    {
        private static readonly Dictionary<string, string> Ru = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["WindowTitle"] = "Демо привязки MVVM",
            ["Language"] = "Язык",
            ["Language_Russian"] = "Русский",
            ["Language_English"] = "Английский",
            ["Tab_DefaultBinding"] = "Привязка по умолчанию",
            ["Tab_TwoWayBinding"] = "Двухсторонняя привязка",
            ["Tab_OneTimeBinding"] = "Одноразовая привязка",
            ["Tab_OneWayBinding"] = "Односторонняя привязка",
            ["Tab_Triggers"] = "Триггеры",
            ["DefaultBinding_Header"] = "DefaultBinding (TextBox, UpdateSourceTrigger по умолчанию — LostFocus)",
            ["DefaultBinding_Description"] = "Сравнение: прямая привязка к свойству окна и привязка к свойству ViewModel.",
            ["DefaultBinding_WindowBinding"] = "Прямая привязка к свойству окна",
            ["DefaultBinding_ViewModelBinding"] = "Привязка через ViewModel",
            ["DefaultBinding_CurrentWindowValue"] = "Текущее значение свойства окна:",
            ["DefaultBinding_CurrentViewModelValue"] = "Текущее значение свойства ViewModel:",
            ["DefaultBinding_LastUpdated"] = "Последнее обновление: {0:T}",
            ["DefaultBinding_Tooltip_Window"] = "Источник обновляется только при потере фокуса (LostFocus — значение по умолчанию).",
            ["DefaultBinding_Tooltip_ViewModel"] = "Та же привязка по умолчанию (LostFocus), но источник — свойство ViewModel.",
            ["DefaultBinding_Note"] = "Пока TextBox в фокусе, источник не обновляется. Значение меняется только при потере фокуса.",
            ["Message_DataSaved"] = "Данные успешно сохранены.",
            ["Button_ShowMessage"] = "Показать сообщение (внешняя библиотека)",
            ["Triggers_Placeholder"] = "Демонстрация триггеров будет реализована здесь.",
            ["OneWay_Placeholder"] = "Демонстрация односторонней привязки будет реализована здесь.",
            ["OneTime_Title"] = "OneTimeBinding (одноразовая привязка)",
            ["OneTime_Description"] = "Дата запуска берётся один раз (Mode=OneTime), далее изменения источника не отражаются в UI.",
            ["OneTime_Compare"] = "Сравнение OneTime и обычной OneWay-привязки",
            ["OneTime_Start"] = "Дата запуска (OneTime)",
            ["OneTime_Current"] = "Текущее время (обновляется каждую секунду)",
            ["OneTime_StartFormat"] = "Запуск: {0:G}",
            ["OneTime_CurrentFormat"] = "Сейчас: {0:T}",
            ["OneTime_Note"] = "Значение \"Дата запуска (OneTime)\" остаётся неизменным, даже если источник меняется после загрузки.",
            ["TwoWay_Title"] = "TwoWayBinding (двухсторонняя привязка)",
            ["TwoWay_Description"] = "Сравнение прямой привязки к окну и привязки к ViewModel с UpdateSourceTrigger=PropertyChanged.",
            ["TwoWay_WindowBinding"] = "Прямая привязка (TwoWay) к свойству окна",
            ["TwoWay_WindowTooltip"] = "Двухсторонняя привязка к свойству окна. Источник обновляется при каждом изменении текста.",
            ["TwoWay_CurrentWindow"] = "Текущее значение свойства окна:",
            ["TwoWay_ViewModelSection"] = "Привязка через ViewModel (Name, IsEnabled, Volume)",
            ["TwoWay_NameCaption"] = "Имя (TextBox, TwoWay, PropertyChanged)",
            ["TwoWay_NameCurrentFormat"] = "Текущее значение",
            ["TwoWay_IsEnabledCaption"] = "Включено (TwoWay к CheckBox)",
            ["TwoWay_VolumeCaption"] = "Громкость (Slider, TwoWay)",
            ["TwoWay_VolumeCurrentFormat"] = "Текущее значение громкости: {0:F0}%",
            ["TwoWay_Note"] = "Двухсторонняя привязка синхронизирует UI и источник. Для TextBox с PropertyChanged обновление идёт на каждый символ.",
            ["OneWay_Title"] = "OneWayBinding (односторонняя привязка)",
            ["OneWay_Description"] = "UI только читает данные из источника. Изменения в поле ввода не влияют на источник.",
            ["OneWay_SourceValue"] = "Значение источника (обновляется таймером каждую секунду)",
            ["OneWay_BoundValue"] = "Значение в TextBlock (OneWay)",
            ["OneWay_UserInput"] = "Поле ввода (не привязано к источнику)",
            ["OneWay_UserInputHint"] = "Текст здесь меняется локально и не влияет на SourceText.",
            ["OneWay_Note"] = "Источник обновляется таймером. TextBlock синхронно меняется, потому что привязка OneWay.",
            ["Triggers_Title"] = "Триггеры (Property/Data/MultiData)",
            ["Triggers_Description"] = "Ниже показаны разные типы триггеров, меняющие стиль в зависимости от состояния.",
            ["Triggers_EnableAlerts"] = "Включить уведомления",
            ["Triggers_Load"] = "Загрузка",
            ["Triggers_ProgressCaption"] = "Прогресс задачи:",
            ["Triggers_StatusCaption"] = "Статус:",
            ["Triggers_TempCaption"] = "Температура:",
            ["Triggers_Ready"] = "Готово к работе",
            ["Triggers_Working"] = "Выполняется...",
            ["Triggers_Overheat"] = "Перегрев",
            ["Triggers_Warning"] = "Внимание: высокая температура и активная загрузка!"
        };

        private static readonly Dictionary<string, string> En = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["WindowTitle"] = "MVVM Binding Demo",
            ["Language"] = "Language",
            ["Language_Russian"] = "Russian",
            ["Language_English"] = "English",
            ["Tab_DefaultBinding"] = "Default Binding",
            ["Tab_TwoWayBinding"] = "Two-Way Binding",
            ["Tab_OneTimeBinding"] = "One-Time Binding",
            ["Tab_OneWayBinding"] = "One-Way Binding",
            ["Tab_Triggers"] = "Triggers",
            ["DefaultBinding_Header"] = "DefaultBinding (TextBox, default UpdateSourceTrigger — LostFocus)",
            ["DefaultBinding_Description"] = "Comparison: direct binding to window property and binding to ViewModel property.",
            ["DefaultBinding_WindowBinding"] = "Direct binding to window property",
            ["DefaultBinding_ViewModelBinding"] = "Binding via ViewModel",
            ["DefaultBinding_CurrentWindowValue"] = "Current window property value:",
            ["DefaultBinding_CurrentViewModelValue"] = "Current ViewModel property value:",
            ["DefaultBinding_LastUpdated"] = "Last updated: {0:T}",
            ["DefaultBinding_Tooltip_Window"] = "The source updates only on focus loss (LostFocus is default).",
            ["DefaultBinding_Tooltip_ViewModel"] = "Same default binding mode (LostFocus), but source is a ViewModel property.",
            ["DefaultBinding_Note"] = "While TextBox has focus, source is not updated. Value changes only after focus is lost.",
            ["Message_DataSaved"] = "Data saved successfully.",
            ["Button_ShowMessage"] = "Show message (external library)",
            ["Triggers_Placeholder"] = "Triggers demo will be implemented here.",
            ["OneWay_Placeholder"] = "One-way binding demo will be implemented here.",
            ["OneTime_Title"] = "OneTimeBinding (one-time binding)",
            ["OneTime_Description"] = "Start time is read once (Mode=OneTime), then source changes are not reflected in UI.",
            ["OneTime_Compare"] = "Comparison of OneTime and regular OneWay binding",
            ["OneTime_Start"] = "Start time (OneTime)",
            ["OneTime_Current"] = "Current time (updates every second)",
            ["OneTime_StartFormat"] = "Start: {0:G}",
            ["OneTime_CurrentFormat"] = "Now: {0:T}",
            ["OneTime_Note"] = "The \"Start time (OneTime)\" value remains unchanged even if source changes after loading.",
            ["TwoWay_Title"] = "TwoWayBinding (two-way binding)",
            ["TwoWay_Description"] = "Comparison of direct window binding and ViewModel binding with UpdateSourceTrigger=PropertyChanged.",
            ["TwoWay_WindowBinding"] = "Direct TwoWay binding to window property",
            ["TwoWay_WindowTooltip"] = "Two-way binding to a window property. Source updates on each text change.",
            ["TwoWay_CurrentWindow"] = "Current window property value:",
            ["TwoWay_ViewModelSection"] = "Binding via ViewModel (Name, IsEnabled, Volume)",
            ["TwoWay_NameCaption"] = "Name (TextBox, TwoWay, PropertyChanged)",
            ["TwoWay_NameCurrentFormat"] = "Current value",
            ["TwoWay_IsEnabledCaption"] = "Enabled (TwoWay to CheckBox)",
            ["TwoWay_VolumeCaption"] = "Volume (Slider, TwoWay)",
            ["TwoWay_VolumeCurrentFormat"] = "Current volume: {0:F0}%",
            ["TwoWay_Note"] = "Two-way binding keeps UI and source synchronized. With PropertyChanged, TextBox updates on every keystroke.",
            ["OneWay_Title"] = "OneWayBinding (one-way binding)",
            ["OneWay_Description"] = "UI only reads data from the source. Editing input does not update the source.",
            ["OneWay_SourceValue"] = "Source value (updated by timer every second)",
            ["OneWay_BoundValue"] = "TextBlock value (OneWay)",
            ["OneWay_UserInput"] = "Input field (not bound to source)",
            ["OneWay_UserInputHint"] = "Text entered here is local and does not affect SourceText.",
            ["OneWay_Note"] = "The source changes by timer. TextBlock updates accordingly because binding is OneWay.",
            ["Triggers_Title"] = "Triggers (Property/Data/MultiData)",
            ["Triggers_Description"] = "Different trigger types below change styles based on state.",
            ["Triggers_EnableAlerts"] = "Enable alerts",
            ["Triggers_Load"] = "Load",
            ["Triggers_ProgressCaption"] = "Task progress:",
            ["Triggers_StatusCaption"] = "Status:",
            ["Triggers_TempCaption"] = "Temperature:",
            ["Triggers_Ready"] = "Ready",
            ["Triggers_Working"] = "Working...",
            ["Triggers_Overheat"] = "Overheat",
            ["Triggers_Warning"] = "Warning: high temperature under active load!"
        };

        public static string GetString(CultureInfo culture, string key)
        {
            var dict = culture != null && culture.Name.StartsWith("en", StringComparison.OrdinalIgnoreCase) ? En : Ru;
            return dict.TryGetValue(key, out var value) ? value : key;
        }
    }
}
